version: "1"
services:
  backExample:
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DB: exampledb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PYTHONUNBUFFERED: 0
    depends_on:
      - db
  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_DB: examen
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password