version: "1"
services:
  examen-1:
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_DB: examen
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password